#!/usr/bin/env bash

# from https://github.com/rycus86/githooks/blob/master/.githooks/pre-commit/has-shell-function-comments
. shell_helpers

for SCRIPT_FILE in `ls | egrep '\.sh$|\.bash$|\.ksh$'`; do
  IFS='\-'

  # shellcheck disable=SC2013
  for LINES in $(grep -hE -B 1 '^.+\(\) {$' "$SCRIPT_FILE"); do
    if [[ -z "$LINES" ]]; then
      continue
    fi

    if ! echo "$LINES" | grep -q '^#'; then
      print_msg red "Missing function header in ${SCRIPT_FILE}:" \
        "$(echo "$LINES" | grep -vE '^\s*$' | sed 's/ {//')"

      HAS_MISSING_HEADERS=1
    fi
  done
  unset IFS
done

if [[ -z "$HAS_MISSING_HEADERS" ]]; then
  print_msg green "All Shell functions have headers"
else
  exit 1
fi
